### ISSUE TITLE
TradeBot won't start 

### ISSUE THREAD

**Issue by mike-hm** [markusaksli/TradeBot#30]
The TradeBot is a great bot - great job but I can't get it running since 06/24/2021. The console opens and nothing appears even after a long wait. Previously, it worked very well. I checked on various operating systems such as Windows 7 x64, Windows Server 2012, Linux Mint 19. JAVA version - 1.8.0_291-b10. Please help. 

![1](https://user-images.githubusercontent.com/86550261/123537927-605d5c80-d732-11eb-8cf4-49fbfaeef5d8.png)

**Comment by markusaksli** [comment]
The bot still seems to work fine from my IDE but the release build won't output anything after starting for me as well.

**Comment by mike-hm** [comment]
So what's the solution to run a bot? Run via IDE? I still can't get it running.

**Comment by markusaksli** [comment]
Fixed by https://github.com/markusaksli/TradeBot/releases/tag/v0.10.1

Seems like some change in the binance API caused this? Not sure because it is still only reproducible in the executable but the latest release should have fixed it (although it only uses a workaround in practice).

Trying to see what exactly causes the issue will likely take a bit more digging but the rework takes priority for now.

**Comment by mike-hm** [comment]
Thank you so much. Great job :)

**Comment by mike-hm** [comment]
Unfortunately, the bot still does not work. Starts but does not set a purchase order. None of the orders were purchased. Below is a screenshot.

![screen](https://user-images.githubusercontent.com/86550261/125322561-3618bb00-e33e-11eb-8f52-0df5a528b425.png)
